name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=tineo_challenge -Dsonar.organization=tineo

      - name: Build jar and package
        run: mvn clean install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ secrets.ECR_URI }}
          ECR_REPOSITORY: challenge
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
  deploy-in-ecs:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition mi-aplicacion --query taskDefinition > task-definition.json
      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: mi-contenedor
          image: ${{ needs.build-and-push-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: mi-servicio-ecs
          cluster: mi-cluster-ecs
          wait-for-service-stability: true

  create-release:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      #- name: Build and package
      #  run: mvn clean install
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Extract version and name from pom.xml
        id: extract
        run: |
          version=$(grep -oP '(?<=<version>).*(?=<\/version>)' pom.xml | tail -n 1)
          version_number=${version%-SNAPSHOT}
          name=$(grep -oP '(?<=<name>).*(?=<\/name>)' pom.xml | head -n 1)
          echo "Extracted version: $version"
          echo "Extracted version_number: $version_number"
          echo "Extracted name: $name"
          echo "::set-output name=VERSION::$version"
          echo "::set-output name=VERSION_NUMBER::$version_number"
          echo "::set-output name=NAME::$name"
      - name: Print extracted information
        run: |
          echo "Extracted version: ${{ steps.extract.outputs.VERSION }}"
          echo "Extracted version_number: ${{ steps.extract.outputs.VERSION_NUMBER }}"
          echo "Extracted name: ${{ steps.extract.outputs.NAME }}"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: ${{ steps.extract.outputs.VERSION_NUMBER }}
          name: ${{ steps.extract.outputs.VERSION_NUMBER }}
          body: deployed ${{ steps.extract.outputs.NAME }}-${{ steps.extract.outputs.VERSION_NUMBER }}
          draft: false
          prerelease: false
          files: target/${{ steps.extract.outputs.NAME }}-${{ steps.extract.outputs.VERSION }}.jar

