name: Deployment

on:
  push:
    branches:
      - main

jobs:

  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/login-action@v1
        with:
          username: AWS
          password: ${{ secrets.AWS_ACCESS_KEY_ID }}:{{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build and tag image
        run: |
          docker build -t challenge:latest .
          docker tag challenge:latest ${{ secrets.ECR_URI }}/challenge:latest

      - name: Push image to ECR
        run: docker push ${{ secrets.ECR_URI }}/challenge:latest


  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Build and package
        run: mvn clean install

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          tag_name: v1.0.0
          name: My Release
          body: This is my first release!
          draft: false
          prerelease: false
          files: target/challenge-0.0.1-SNAPSHOT.jar

